# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Weiwei Chen
#tagline:          'A Jekyll theme'
description:      'Anyone who understands me eventually recognizes them as nonsensical, when he has used them—as steps—to climb beyond them'
url:              http://chenww.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
markdown:         kramdown

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
